<template>
  <div class="pad20">
    <el-row :gutter="20" class="marginbot10">
      <el-col :span="8">
        <label>年级:</label>
        <span>2018级</span>
      </el-col>
      <el-col :span="8">
        <label>班级:</label>
        <span>电气1班</span>
      </el-col>
      <el-col :span="8">
        <label>班主任:</label>
        <span>张三</span>
      </el-col>
    </el-row>
    <el-row class="marginbot20">
      <label>备注:</label>
      <span>备注信息.....</span>
    </el-row>

    <el-table
      :data="tableData1"
      border
      height="700"
      >
      <el-table-column
        prop="z"
        label="洲"
        width="120">
      </el-table-column>
      <el-table-column
        prop="no"
        label="序号"
        width="120">
      </el-table-column>
      <el-table-column
        prop="gj"
        label="国家"
        width="">
      </el-table-column>
      <el-table-column
        prop="men"
        label="男(人数)"
        width="120">
      </el-table-column>
      <el-table-column
        prop="women"
        label="女(人数)"
        width="120">
      </el-table-column>
      <el-table-column
        prop="sum"
        label="总"
        width="120">
      </el-table-column>
    </el-table>
  </div>
</template>

<script>
  export default {
    name: 'nation',
    data(){
      return{
        tableData1:[
          {
            z:"亚洲",
            no:"1",//序号
            gj:"阿富汗",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"亚洲",
            no:"2",//序号
            gj:"巴基斯坦",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"亚洲",
            no:"3",//序号
            gj:"尼泊尔",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"亚洲",
            no:"4",//序号
            gj:"印度",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"亚洲",
            no:"5",//序号
            gj:"印度尼西亚",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"非洲",
            no:"6",//序号
            gj:"埃塞俄比亚",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"非洲",
            no:"7",//序号
            gj:"博茨瓦纳",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"非洲",
            no:"8",//序号
            gj:"布隆迪",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"非洲",
            no:"9",//序号
            gj:"加纳",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"非洲",
            no:"10",//序号
            gj:"津巴布韦",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"非洲",
            no:"11",//序号
            gj:"喀麦隆",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"非洲",
            no:"12",//序号
            gj:"肯尼亚",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"非洲",
            no:"13",//序号
            gj:"卢旺达",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"非洲",
            no:"14",//序号
            gj:"马拉维",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"非洲",
            no:"15",//序号
            gj:"纳米比亚",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"非洲",
            no:"16",//序号
            gj:"南非",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"非洲",
            no:"17",//序号
            gj:"尼日利亚",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"非洲",
            no:"18",//序号
            gj:"苏丹",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"非洲",
            no:"19",//序号
            gj:"南苏丹",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"非洲",
            no:"20",//序号
            gj:"索马里",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"非洲",
            no:"21",//序号
            gj:"坦桑尼亚",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"非洲",
            no:"22",//序号
            gj:"赞比亚",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"美洲",
            no:"23",//序号
            gj:"加拿大",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"美洲",
            no:"24",//序号
            gj:"美国",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
          {
            z:"欧洲",
            no:"25",//序号
            gj:"英国",//国家
            men:"2",
            women:"2",
            sum:"4"
          },
        ]
      }
    }
  }
</script>

<style scoped>

</style>
